### ISSUE TITLE
setting non-master and non-data node causes discovery to fail

### ISSUE THREAD

**Issue by jlintz** [elastic/elasticsearch-cloud-aws#111]
I _think_ this is from the aws discovery plugin.  I've got 5 nodes currently, 3 data nodes and 2 non-data.  I wanted to ensure the data nodes were never master and have the 2 non-data nodes act as the masters.  When I set `master: false` on the data nodes and restart, the nodes cannot rejoin a cluster , just see `no known master node, scheduling a retry`, over and over again in the logs.  

```
cloud:
  aws:
    region: us-east-1
cluster:
  name: logstash_es
  routing:
    allocation:
      awareness:
        attributes: rack_id
discovery:
  ec2:
    groups: logstash_es
    ping_timeout: 60s
  type: ec2
  zen:
    minimum_master_nodes: 2
    multicast:
      enabled: false
node:
  data: false
  master: false
  name: logstashweb01-logstash_es
  rack_id: us-east-1b
path:
  data: /usr/share/elasticsearch/data/logstash_es
  logs: /mnt/logs/elasticsearch
```
