### ISSUE TITLE
Elasticsearch 2.2.0 installation error

### ISSUE THREAD

**Issue by zukeru** [elastic/elasticsearch-cloud-aws#267]
I am trying to install the cloud plugin with the latest version of elasticsearch 2.2.0. However, I'm getting an error when I try to install it:

`: ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin `

Here is the command I'm running to install it:
```

#### Plugins
## AWS Discovery
# https://github.com/elasticsearch/elasticsearch-cloud-aws
ec2_version: 2.7.1

- name: Install EC2 esPluginEC2
  command: bin/plugin install elasticsearch/elasticsearch-cloud-aws/{{ ec2_version }} chdir=/usr/share/elasticsearch
  tags:
    - elasticsearch
    - system
    - build
```

I found someone who said there was a method to fix it:

```
<?xml version="1.0"?>
<assembly>
    <id>plugin</id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <files>
        <file>
            <source>${project.basedir}/plugin-metadata/plugin-descriptor.properties</source>
            <outputDirectory></outputDirectory>
            <filtered>true</filtered>
        </file>
    </files>
    <fileSets>
        <fileSet>
            <directory>src/main/config</directory>
            <outputDirectory>config</outputDirectory>
        </fileSet>
        <fileSet>
            <directory>src/main/bin</directory>
            <outputDirectory>bin</outputDirectory>
        </fileSet>
    </fileSets>
    <dependencySets>
        <dependencySet>
            <outputDirectory>/</outputDirectory>
            <useProjectArtifact>true</useProjectArtifact>
            <useTransitiveFiltering>true</useTransitiveFiltering>
            <useTransitiveDependencies>true</useTransitiveDependencies>
        </dependencySet>
    </dependencySets>
</assembly>
```

does anyone know how else to do this? I would really like to avoid manually setting up an xml file for install.
