### ISSUE TITLE
Update to Elasticsearch 0.90.3

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-cloud-aws#31]
Issue reported in https://groups.google.com/d/msg/elasticsearch/bpdetIvIg5M/cMAUGwhRVf0J

No problem with elasticsearch 0.90.2 and the cloud-aws 1.12.0 plugin (other than the usual node discovery flakiness), but I'm unable to get elasticsearch 0.90.3 to start:

Initialization Failed ...

```
1) IllegalStateException[This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.]2) NoSuchMethodError[org.elasticsearch.discovery.zen.ZenDiscovery.<init>(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/cluster/ClusterName;Lorg/elasticsearch/threadpool/ThreadPool;Lorg/elasticsearch/transport/TransportService;Lorg/elasticsearch/cluster/ClusterService;Lorg/elasticsearch/node/settings/NodeSettingsService;Lorg/elasticsearch/cluster/node/DiscoveryNodeService;Lorg/elasticsearch/discovery/zen/ping/ZenPingService;)V]
```

Do I need to wait for a new version of cloud-aws, or is there some other problem here?

My /etc/elasticsearch/elasticsearch.yml:

``` yml
cluster.name: foo

plugin.mandatory: cloud-aws,lang-javascript

cloud:
    aws:
        access_key: ********
        secret_key: ********
        region: us-east-1

discovery:
    type: ec2
    ec2:
        ping_timeout: 15s

gateway:
    type: s3
    s3:
        bucket: bar
```

**Comment by jacobwgillespie** [comment]
For anyone (like me) who is seeing this error, my fix was to update to the correct version (as indicated by the README) - I accidentally updated Elasticsearch to 1.5.0 without updating elasticsearch-cloud-aws.

**Comment by rabidscorpio** [comment]
@jacobwgillespie ha, thanks for pointing this out, I did the same thing!

**Comment by hjc1710** [comment]
I just ran into this issue today, and it had nothing to do with mis-matched ES/Plugin versions. This error is also thrown if your *config* values for the cloud-aws plugin are not correct.

What I had:

```yaml
cloud:
  aws:
    access_key: XXX
    secret: XXX
    region: us-east-1
```

What I needed:

```yaml
cloud:
  aws:
    access_key: XXX
    secret_key: XXX
    region: us-east-1
```

The major difference between the two of them being `cloud.aws.secret` in the first, non-working example; which is changed to `cloud.aws.secret_key` in the second, working example.

So, apparently, this exact same error is what you'll get if you've completely borked your `cloud-aws` config. So, keep that in mind!

Maybe in a future release, if you could detect a bad config state like this (access key is present, but secret key is missing) and throw an error, that would be pretty great. Alternatively, implementing it so that an error is thrown if any unknown string appears in the `cloud.aws` namespace would work just as well (so, an error would have been thrown because `cloud.aws.secret` is not a recognized and valid key), but I don't know how feasible that is to do. Just some food for thought!

Hopefully someone finds this useful!
