### ISSUE TITLE
respository s3

### ISSUE THREAD

**Issue by jurgenweber** [elastic/elasticsearch-cloud-aws#94]
I am trying to get s3 repository configuration working and I must admit I am finding the documentation hard to follow, firstly my configuration file I have added:

```
repositories:
  s3:
    base_path: production
    bucket: searchidx
    region: eu-west-1
  type: s3
```

what else do I need? Looking in the debug log nothing is happening and my bucket is empty (yes I created the bucket)
